### ISSUE TITLE
Freeling 2.1 without documentation

### ISSUE THREAD

**Issue by mnavasloro** [hllorens/otip#2]
Hello,

I am trying to install Freeling 2.1 to use TipSem for Spanish, but I am unable to install Freeling due to the lack of documentation for that version/the limitation on the systems that support it.

Is it possible to use other library instead of Freeling 2.1 or is there any demo/service I where I can test TipSem for Spanish? (I am doing a state of the art)

Best regards

**Comment by hllorens** [comment]
Hi, it's been a while since I ran this for the last time.
I cannot access the old demo online from the University of Alicante.

I see 2 solutions:
1) You could adapt the code to new  Freeling versions
2) Ask my supervisors that are still working at the DLSI department: Estela Saquete or Borja Navarro

**Comment by mnavasloro** [comment]
Thank you for your answer. I contacted your supervisors and they told me the demo is not available anymore and also recommended to try with Freeling 4.0, so I will do so.

Thank you very much!

**Comment by hllorens** [comment]
Let me know how it goes and if there is no luck perhaps in a month or so I might be able to review the situation and help.

**Comment by mnavasloro** [comment]
Hello again,

I finally installed Freeling 4.0 and I found this error:


```
File: /XXX/LINUX-SETUP-TIPSEM/TIPSEM/tmp2019.06.19-11.33.55.031 Language:es
Errors found (TempEval):
        java.lang.NullPointerException (Reading line 0 /XXX/LINUX-SETUP-TIPSEM/TIPSEM/tmp2019.06.19-11.33.55.031_TIPSemB_features/tmp2019.06.19-11.33.55.031.TempEval2-features-annotatedWith-CRFmodel-TIPSemB_rec_timex_ES-IOB2checked.TempEval2-features-annotatedWith-attribs.TempEval2-features-annotatedWith-attribs-append-merged-ids)

Errors found (CRF++):
        java.lang.Exception: Template file (TIPSemB_categ_e-t_ES.CRFmodel) not found.
Errors found (CRF++):
        java.lang.Exception: Template file (TIPSemB_categ_e-dct_ES.CRFmodel) not found.
Errors found (TempEval):
        java.lang.NullPointerException (Reading line 0)

Errors found (TempEval):
        java.lang.NullPointerException (Reading line 0)

null

Errors found (OptionHandler):
        java.lang.NullPointerException

Done in 0.00 sec!

Result:

Errors found:
        tmp2019.06.19-11.33.55.031.tml (No such file or directory)
```


When I went to the program-data, I discovered that those missing files exist for English but not for Spanish:

```
/LINUX-SETUP-TIPSEM/TIPSEM/program-data/CRF++/models$ ls
TIPSemB_categ_e-dct_EN.CRFmodel   TIPSemB_class_timex_EN.CRFmodel  TIPSem_categ_e-dct_EN.CRFmodel   TIPSem_rec_event_EN.CRFmodel
TIPSemB_categ_e-main_EN.CRFmodel  TIPSemB_class_timex_ES.CRFmodel  TIPSem_categ_e-main_EN.CRFmodel  TIPSem_rec_event_ES.CRFmodel
TIPSemB_categ_e-main_ES.CRFmodel  TIPSemB_rec_event_EN.CRFmodel    TIPSem_categ_e-main_ES.CRFmodel  TIPSem_rec_timex_EN.CRFmodel
TIPSemB_categ_e-sub_EN.CRFmodel   TIPSemB_rec_event_ES.CRFmodel    TIPSem_categ_e-sub_EN.CRFmodel   TIPSem_rec_timex_ES.CRFmodel
TIPSemB_categ_e-sub_ES.CRFmodel   TIPSemB_rec_timex_EN.CRFmodel    TIPSem_categ_e-sub_ES.CRFmodel   TIPSem_timen_timex_EN.CRFmodel
TIPSemB_categ_e-t_EN.CRFmodel     TIPSemB_rec_timex_ES.CRFmodel    TIPSem_categ_e-t_EN.CRFmodel
TIPSemB_class_event_EN.CRFmodel   TIPSemB_timen_timex_EN.CRFmodel  TIPSem_class_event_EN.CRFmodel
TIPSemB_class_event_ES.CRFmodel   TIPSemB_timen_timex_ES.CRFmodel  TIPSem_class_timex_EN.CRFmodel
```

Can I get them somewhere?

Best regards

**Comment by hllorens** [comment]
Awesome!
I will have a look now... alternatively you could disable them if you don't need to annotate links. Do you need it?
Thanks
Hector

**Comment by hllorens** [comment]
Mmm I see what happens... I only obtained them for SVM (look at the SVM folder).
We should document that... we need (for es-es) to run the link annotation using SVM and not CRF...
Makes sense? do you know how?
We can have a quick call and do it together and I will document it (unless you want to contribute to this project with that, which I would be completely fine with and give you credit for it)

**Comment by hllorens** [comment]
So here is how more or less:

-a,--action Action/s (annotatecrf, annotate)      --> annotate means using SVM (I think, it was 10 years ago, hehe)

Then,
-ap,--action_parameters Actions can have comma separated params Valid parameters are: dct (default: today date) entities (default: timex, event, tlink) inputf (default: plain) options: plain, te3input, tml, isotml

This would allow you for example to take tml input annotated with CRF with only timex and event and then use SVM only for tlink.

**Alternatively and even better (optional)**:  we could edit the code to say when a model is missing ask the user if they want to try SVM for that missing part. And then if the SVM does not exist either then break with a meaningful error. Wdyt? (Shouldn't be very difficult)

**Comment by mnavasloro** [comment]
Hi again,

I tried using SVM and it did not work either, also annotating just with timex did not work. Maybe is a problem with Freeling? I installed version 4.0 and there might be some incompatibilities we are not considering? 

Best,

María

**Comment by hllorens** [comment]
María that might be possible. Do you have the log (error message)?
Does it work with SVM and English?
I am tempted to say that a live debugging version with the two of us will be the best todo.

**Comment by hllorens** [comment]
Closing this old issue.
