### ISSUE TITLE
Maven dependencies

### ISSUE THREAD

**Issue by Klaifer** [hllorens/otip#4]
Hello, I'm trying to install TIPSem and I'm having some missing dependencies issues.
Can you point out where to find this?

- com.cognitionis:utils-basickit:jar:1.0.1
- com.cognitionis:nlp-files:jar:1.0.0
- com.cognitionis:timeml-basickit:jar:1.0.0
- com.cognitionis:knowledgek:jar:1.0.0
- com.cognitionis:external-tools:jar:1.0.0
- com.cognitionis:feature-builder:jar:1.0.0
- com.cognitionis:wiki-basickit:jar:1.0.0

**Comment by hllorens** [comment]
Hi @Klaifer 

You can have a look at:
- https://github.com/hllorens/cognitionis-mvn-repo
   - e.g., https://github.com/hllorens/cognitionis-mvn-repo/tree/master/releases/com/cognitionis/utils-basickit/1.0.1
   - e.g., https://github.com/hllorens/cognitionis-mvn-repo/tree/master/releases/com/cognitionis/feature-builder/1.0.0
- https://github.com/hllorens/cognitionis-nlp-libraries

BR

**Comment by Klaifer** [comment]
The installation worked.
Thank you for your quick answer.

**Comment by hllorens** [comment]
Perfect. Closing the issue as fixed.
Thanks to your input, I improved the README so that it mentions the location of these dependencies.
